"""
Add metrics and metric_types table

Revision ID: 1bb14b173472
Revises:     c3dad71f8e6b
Create Date: 2025-07-30 11:17:35.354218
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa



# Revision identifiers, used by Alembic.
revision = '1bb14b173472'
down_revision = 'c3dad71f8e6b'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_type_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('aggregation_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_types')),
    sa.UniqueConstraint('metric_type_name', name=op.f('uq_metric_types_metric_type_name'))
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_history_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], name=op.f('fk_metrics_metric_type_id_metric_types')),
    sa.ForeignKeyConstraint(['run_history_id'], ['run_histories.id'], name=op.f('fk_metrics_run_history_id_run_histories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('metric_types')
    # ### end Alembic commands ###
